services:
  web_frontend:
    build:
      context: ..
      dockerfile: web/Dockerfile.dev
    container_name: web_frontend
    restart: always
    ports:
      - "13103:3000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /workspace/web
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./package.json
