services:
  web_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PMI_API_URL: http://api-pmi.topvnsport.com
        VITE_OMS_API_URL: http://api-oms.topvnsport.com
        VITE_WMS_API_URL: http://api-wms.topvnsport.com
    container_name: web_frontend
    restart: always
    networks:
      - pmi_default

networks:
  pmi_default:
    external: true
